import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { Jost } from "next/font/google";
import Soria from "next/font/local";


const jost = Jost({
	subsets: ["latin"],
	variable: "--font-jost",
	display: "swap",
});

const soria = Soria({
  src: './font/soria-font.ttf',
  variable: "--font-soria",
  display: 'swap',
});


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${jost.variable} ${soria.variable}`}>
			<body>{children}</body>
		</html>
	);
}
