// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  about_section: dynamic(() => import("./AboutSection")),
  landing: dynamic(() => import("./Landing")),
  selected_works: dynamic(() => import("./SelectedWorks")),
};
