// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_section: dynamic(() => import("./AboutSection")),
  crafts_gallery: dynamic(() => import("./CraftsGallery")),
  landing: dynamic(() => import("./Landing")),
  project_gallery: dynamic(() => import("./ProjectGallery")),
  project_info: dynamic(() => import("./ProjectInfo")),
  selected_works: dynamic(() => import("./SelectedWorks")),
  works_gallery: dynamic(() => import("./WorksGallery")),
};
